//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _min.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Connstrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Connstrings defaultInstance = ((Connstrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Connstrings())));
        
        public static Connstrings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
